service: dafa-server

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  memorySize: 128
  environment:
    NODE_ENV: production

functions:
  verify-token:
    handler: src/middleware/VerifyToken.auth

  anonymous:
    handler: src/bin/www.handler
    events:
      - http:
          path: /api/users/login
          method: ANY
          cors: true

  app:
    handler: src/bin/www.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
             allowCredentials: true
          authorizer: verify-token
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
          authorizer: verify-token

plugins:
  - serverless-offline

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
