service: dafa-server

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  memorySize: 128

functions:
  verify-token:
    handler: src/middleware/VerifyToken.auth

  anonymous:
    handler: src/bin/www.handler
    events:
      - http:
          path: /api/users/login
          method: ANY
          cors: true

  app:
    handler: src/bin/www.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
          authorizer: verify-token
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
          authorizer: verify-token

plugins:
  - serverless-offline
