service: dafa-server
custom:
  # Enable or disable caching globally
  apiGatewayCaching:
    enabled: false

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  memorySize: 128
  environment:
    NODE_ENV: ${env:NODE_ENV}
    SECRET: ${env:SECRET}
    CLIENT_SIDE_URL: ${env:CLIENT_SIDE_URL}
    MONGODB_URI: ${env:MONGODB_URI}

functions:
  authorizer:
    handler: src/middleware/verifyToken.authorizer

  anonymous:
    handler: src/bin/www.handler
    events:
      - http:
          path: /api/users/login
          method: ANY
          cors: true

  app:
    handler: src/bin/www.handler
    events:
      - http:
          path: /
          method: ANY
          authorizer: authorizer
          cors:
            origin: ${env:CLIENT_SIDE_URL}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: /{proxy+}
          method: ANY
          authorizer: authorizer
          cors:
            origin: ${env:CLIENT_SIDE_URL}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

plugins:
  - serverless-offline
  - serverless-api-gateway-caching

resources:
  Resources:
    GatewayResponse:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'https://dafa-web.firebaseapp.com'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Origin, X-Request-With, Content-Type, Accept, Authorization, X-Amz-Date, X-Api-Key, X-Amz-Security-Token, X-Amz-User-Agent, Access-Control-Allow-Credentials'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: "ApiGatewayRestApi"
        StatusCode: "401"
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'https://dafa-web.firebaseapp.com'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Origin, X-Request-With, Content-Type, Accept, Authorization, X-Amz-Date, X-Api-Key, X-Amz-Security-Token, X-Amz-User-Agent, Access-Control-Allow-Credentials'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'OPTIONS,GET,HEAD,PUT,PATCH,POST'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
